FROM adoptopenjdk/openjdk8:latest

RUN mkdir /opt/app
COPY Main.java /opt/app
WORKDIR /opt/app
RUN javac Main.java
#"-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap" for adoptopenjdk docker
CMD ["java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap", "Main"]